version: 2
jobs:
  one:
    steps:
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: sudo /opt/google-cloud-sdk/bin/gcloud config set project $GCLOUD_PROJECT

      
